version: '3.8'

services:
  backend:
    build:
      context: .
    container_name: news-backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=news_app
      - DB_USERNAME=new_root
      - DB_PASSWORD=123
    ports:
      - "8000:9000"  # Ensure this maps the right internal port for Laravel
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - laravel-net

  db:
    image: mysql:8
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news_app
      MYSQL_USER: new_root
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"  # Optional: Keep this if you want external access to MySQL on port 3307
    networks:
      - laravel-net
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local

networks:
  laravel-net:
    driver: bridge
